CREATE DATABASE IF NOT EXISTS sample_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE sample_db;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
